// Las 50 razones para Alma.
// Solo cambia los textos de cada razon: { razon: "..." }

window.RAZONES = [
  { razon: "Porque tu risa hace que cualquier mal día valga la pena." },
  { razon: "Porque eres el mejor regalito que me dio la vida." },
  { razon: "Porque me miras como nadie me miró nunca." },
  { razon: "Porque tus abrazos curan hasta los peores días." },
  { razon: "Porque haces que quiera ser una mejor persona, solo para estar a tu lado." },
  { razon: "Porque hasta el gatito gris te eligió como su humana favorita (y tiene buen gusto)." },
  { razon: "Porque tu voz es mi sonido favorito en el mundo." },
  { razon: "Porque cerca o lejos, siempre me haces sentir acompañado." },
  { razon: "Porque celebras mis logros como si fueran tuyos." },
  { razon: "Porque se te iluminan los ojitos cuando hablas de lo que te gusta." },
  { razon: "Porque la forma en que cuidas a los que amas es admirable." },
  { razon: "Porque hasta enojada eres linda y lo sabes." },
  { razon: "Porque este primer año juntas fue lo más bonito, y esto recién empieza." },
  { razon: "Porque me das paz, y eso vale más que cualquier cosa." },
  { razon: "Porque piensas en mí incluso cuando no lo digo en voz alta." },
  { razon: "Porque tu 'te amo' me acompleta el alma entera." },
  { razon: "Porque eres valiente aunque no te des cuenta." },
  { razon: "Porque haces que lo simple se vuelva especial." },
  { razon: "Porque cuando comparto mis sueños contigo, se vuelven más grandes." },
  { razon: "Porque te quiero en mis mañanas, en mis noches y en todo lo que hay en medio." },
  { razon: "Porque hasta tu apoyo en un mensajito me levanta." },
  { razon: "Porque te mereces todas las cosas bonitas del mundo y quiero ser quien te las dé." },
  { razon: "Porque cuando tú estás, todo está." },
  { razon: "Porque me enseñaste que querer bien sí se puede." },
  { razon: "Porque nuestros planes juntitos me dan ganas de futuro." },
  { razon: "Porque te quiero los días buenos, los malos y los más o menos." },
  { razon: "Porque eres mi persona favorita para no hacer nada." },
  { razon: "Porque tu corazón es más grande de lo que imaginas." },
  { razon: "Porque aunque a veces no esté presente, te llevo conmigo siempre." },
  { razon: "Porque eres calma en medio de mi tormenta." },
  { razon: "Porque me encanta cómo dices mi nombre." },
  { razon: "Porque el gatito gris ronronea más cuando estás tú." },
  { razon: "Porque sueñas bonito y me encanta escucharte." },
  { razon: "Porque no hay meme, canción ni lugar que no me recuerde a ti." },
  { razon: "Porque haces que 'nosotros' sea mi palabra favorita." },
  { razon: "Porque confías en mí, y eso no lo cambio por nada." },
  { razon: "Porque tu amor me hace creer que todo va a estar bien." },
  { razon: "Porque te quiero en pasado, en presente y en futuro." },
  { razon: "Porque me conoces mejor que nadie." },
  { razon: "Porque tu cariño no tiene fecha ni horario." },
  { razon: "Porque hasta lo más chiquito que haces, lo haces con mucho amor." },
  { razon: "Porque el primer año contigo fue apenas el capítulo uno." },
  { razon: "Porque me haces reír cuando ya no me quedaba risa." },
  { razon: "Porque tu '¿cómo estás?' sincero vale oro." },
  { razon: "Porque vamos a cumplir muchos, muchos, muchos años más juntitos." },
  { razon: "Porque cuando imagino el futuro, siempre apareces tú." },
  { razon: "Porque eres mi lugar seguro." },
  { razon: "Porque cuidas de nosotros con un amor enorme." },
  { razon: "Porque no necesito un día especial para recordártelo... pero hoy toca." },
  { razon: "Porque simplemente, eres tú. Y eso lo es todo, almita." }
];
